api_platform:
    defaults:
        route_prefix: '/v1'
    exception_to_status:
        'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
        'ApiPlatform\Core\Validator\Exception\ValidationException': 422
        'Symfony\Component\Serializer\Exception\NotNormalizableValueException': 422
        
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    show_webby: false
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    formats:
        json:
            mime_types:
                - application/json
        jsonld:
            mime_types:
                - application/ld+json
        html:
            mime_types:
                - text/html

    

